### ISSUE TITLE
Add AltSoftSerial

### ISSUE THREAD

**Issue by aufdenkampe** [EnviroDIY/Libraries#7]
A lot of our stuff now depends on https://github.com/PaulStoffregen/AltSoftSerial

Let's add it, before we issue our first release (#5).
@SRGDamia1, I'll try to do this, as a learning opportunity.

**Comment by SRGDamia1** [comment]
Are you ok doing this?  You need to do a "git add submodule" command and then also manually update the library.json file.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for asking! I wanted to use this as an opportunity to learn how to do it.
I got some good guidance from:
* https://gist.github.com/gitaarik/8735255
* https://git-scm.com/docs/git-submodule
Also these might be helpful.
* https://blog.github.com/2016-02-01-working-with-submodules/
* https://git-scm.com/book/en/v2/Git-Tools-Submodules

@SRGDamia1, so how do I create the new "carefully crafted -->->link<-<--" and also the Travis stuff? Can you do that today, and also provide me an explanation for next time? 
I would like to get a "Release" out by Monday, but I also want to keep learning.
Thanks.

**Comment by aufdenkampe** [comment]
@SRGDamia1, wow! You're fast! Does https://github.com/EnviroDIY/Libraries/commit/79af8c17a512f14612540ee2248d5743341a9d93 do it?

**Comment by SRGDamia1** [comment]
The link just goes to the libraries.zip, which is updated every time a Travis run is triggered.  (By a push, a pull request, or manually.)  All the commits you see with a message like "Updated submodules and zip (Travis build 178) [ci skip]" are commits actually made by Travis, using my credentials.  (The encrypted credentials are in id_rsa.enc.)  So, no, I'm not fast, your push just triggered a new run of the script.  The same script also updates all of the submodules to the current head of whatever branch they're pulling.  That's why the SDI-12 libraries all were updated.  You can run the script any time you want to update everything by going to https://travis-ci.org/EnviroDIY/Libraries and hitting "restart build."

The library.json file that I set up for PlatformIO still needs to be manually updated.  I can do that quickly.  I used to have it updated via script, but it became more hassle to keep that script working than to just manually update the json.

Oh, and the ReadMe should be updated.  I'll do that.

**Comment by aufdenkampe** [comment]
Cool! Thanks for that explanation, and for the offer to update the PlatformIO & ReadMe files.

**Comment by SRGDamia1** [comment]
Closed with 85299cf177f0d22803b271b1c6a57982b20ac362
