### ISSUE TITLE
Libraries to add to carefully crafted link

### ISSUE THREAD

**Issue by fisherba** [EnviroDIY/Libraries#8]
Hi @SRGDamia1, I was working with a student this afternoon who isn't using PlatformIO. He downloaded the most recent Libraries to work with the most recent Modular repo, and he needed to manually add the following libraries:
https://github.com/adafruit/Adafruit_MPL115A2
https://github.com/EnviroDIY/KellerModbus

**Comment by SRGDamia1** [comment]
All you have to do is add the new libraries as submodules to this "Libraries" repo and then they will automatically be put into the zip when Travis is run after you push the changes.  The new libraries should also be manually added to the "dependencies" in the library.json.  If you want to update the zip without adding new libraries, you can also open and re-run the Travis job from the last commit and Travis will update the zip and re-commit it.

Anyway, I've done it and everything should be up-to-date now in the zip.  And in the future, I think @aufdenkampe said he'd take over maintaining this repo because I never use the Arduino IDE so I don't think of updating libraries this way very often.

**Comment by aufdenkampe** [comment]
Thank you @SRGDamia1. 
Yes, I did say that I would do it in the future, and I even wanted to issue an official release (see #5). Hopefully next week, after everything gets deployed!
